### ISSUE TITLE
How to convert exported OpenFOAM mesh file to gmsh -2 format ".msh2"

### ISSUE THREAD

**Issue by alisheikholeslam** [nschloe/meshio#1039]
Open source CFD software "OpenFOAM" can export a few mesh file types:
1) ansys fluent software ".msh"
2) Starmesh software ".vrt" for vertices, ".cel" for elements, and ".bnd" for boundary
3) ".VTK" format

I need to convert one of this types to gmsh format which can be used by FiPy library in python, '".msh2" format'.

I would be grateful if you could help me to solve this problem. The exported files are attached to the link below, download links will be shown by clicking on "دریافت لینک دانلود" :

https://s17.picofile.com/file/8426414576/OF_Cylinder.msh.html

https://s17.picofile.com/file/8426414642/meshExport.vrt.html

https://s17.picofile.com/file/8426414676/meshExport.cel.html

https://s17.picofile.com/file/8426414684/SandPro7_0.vtk.html

---

I have used this library, but there were some problems.
when I try to open the ".msh" file, which is exported for fluent, below error was appeared:

As it is written in linke `https://pypi.org/project/meshio/1.8.9/` Ansys mesh can be read and converted by "meshio" but the error below is appeared:
```
mesh = meshio.read("OF_Cylinder.msh", file_format= "ansys-ascii")

ERROR: 
Traceback (most recent call last):
  File "C:/Users/Ali/Desktop/mesh change.py", line 5, in <module>
    mesh = meshio.read("OF_Cylinder.msh", file_format= "ansys-ascii")
  File "C:\Python27\lib\site-packages\meshio\helpers.py", line 176, in read
    return format_to_reader[file_format].read(filename)
  File "C:\Python27\lib\site-packages\meshio\ansys_io.py", line 318, in read
    key, data = _read_cells(f, line)
  File "C:\Python27\lib\site-packages\meshio\ansys_io.py", line 131, in _read_cells
    assert key != "mixed"
AssertionError
```
---

```
mesh = meshio.read("OF_Cylinder.msh")

ERROR=
Traceback (most recent call last):
  File "C:/Users/Ali/Desktop/mesh change.py", line 5, in <module>
    mesh = meshio.read("OF_Cylinder.msh")
  File "C:\Python27\lib\site-packages\meshio\helpers.py", line 176, in read
    return format_to_reader[file_format].read(filename)
  File "C:\Python27\lib\site-packages\meshio\msh_io\main.py", line 15, in read
    mesh = read_buffer(f)
  File "C:\Python27\lib\site-packages\meshio\msh_io\main.py", line 31, in read_buffer
    assert line == "$MeshFormat"
AssertionError
```
---

for Starmesh mesh type files, there are two seperated files for nodes and elements, that could not be converted directly.

---

".VTK" format has been read by meshio, but how to convert in to the -2 format one, directly

```
mesh = meshio.read("SandPro.vtk")
msh = meshio.write("mesh.msh", mesh, file_format="gmsh2-ascii")       worked
```
```
meshio-convert SandPro.vtk SandPro.msh                     didn't work

  File "C:/Users/Ali/Desktop/mesh change.py", line 12
    meshio-convert SandPro.vtk SandPro.msh
                         ^
SyntaxError: invalid syntax
```

**Comment by nschloe** [comment]
Please attach the files as a zip file instead of providing a link.

**Comment by nschloe** [comment]
Also, you seem to be using a years-old version of meshio. Please upgrade first.

**Comment by alisheikholeslam** [comment]
> Also, you seem to be using a years-old version of meshio. Please upgrade first.

I'm using the last version of meshio 4.3.10 by python 3.8 too, but due to ITASCA PFC embedded python 2.7 version meshio version 2.3.10 is installed automatically in pycharm and couldn't update to 4.3.10. I don't know about this version Shortcomings than version 4.3.10. Is there any newer version of meshio which is compatible with python 2.7?

**Comment by alisheikholeslam** [comment]
> Please attach the files as a zip file instead of providing a link.

[mesh.zip](https://github.com/nschloe/meshio/files/6056797/mesh.zip)

**Comment by alisheikholeslam** [comment]
By mesh file that I created in gmsh 2 format, the following error appeared in the PFC software, when It was called by FiPy library. I would be appreciated if you could advice me to solve this error:

File "C:\Program Files\Itasca\PFC500\exe64\python27\lib\site-packages\fipy\meshes\factoryMeshes.py", line 111, in Grid3D
if numerix.getShape(dx) == () File "C:\Program Files\Itasca\PFC500\exe64\python27\lib\site-packages\fipy\tools\numerix.py", line 242, in getShape
raise AttributeError, "No attribute 'shape'"
AttributeError: No attribute 'shape'

**Comment by nschloe** [comment]
> Is there any newer version of meshio which is compatible with python 2.7?

If you need to use Python 2.7, you're basically on your own. I don't know of any significant Python project (including Python itself) that still supports 2.7.

**Comment by nschloe** [comment]
I just tried and the latest version of meshio works fine with the meshes you provide:
```
meshio-info Ansys/OF_Cylinder.msh -i ansys
```
```
WARNING:root:Zone specification not supported yet. Skipping.
WARNING:root:Zone specification not supported yet. Skipping.
WARNING:root:Zone specification not supported yet. Skipping.
WARNING:root:Zone specification not supported yet. Skipping.
WARNING:root:Zone specification not supported yet. Skipping.
<meshio mesh object>
  Number of points: 440664
  Number of cells:
    quad: 1252944
    quad: 10080
    quad: 10080
    quad: 14112
```
It looks like you'll have to try and upgrade.

**Comment by alisheikholeslam** [comment]
I'm facing with this two errors when using meshio 2.3.10 in python 2.7

> mesh = meshio.read("OF_Cylinder.msh", file_format= "ansys-ascii")
> 
> ERROR: 
> Traceback (most recent call last):
>   File "C:/Users/Ali/Desktop/mesh change.py", line 5, in <module>
>     mesh = meshio.read("OF_Cylinder.msh", file_format= "ansys-ascii")
>   File "C:\Python27\lib\site-packages\meshio\helpers.py", line 176, in read
>     return format_to_reader[file_format].read(filename)
>   File "C:\Python27\lib\site-packages\meshio\ansys_io.py", line 318, in read
>     key, data = _read_cells(f, line)
>   File "C:\Python27\lib\site-packages\meshio\ansys_io.py", line 131, in _read_cells
>     assert key != "mixed"
> AssertionError
> ```
> 
> ```
> mesh = meshio.read("OF_Cylinder.msh")
> 
> ERROR=
> Traceback (most recent call last):
>   File "C:/Users/Ali/Desktop/mesh change.py", line 5, in <module>
>     mesh = meshio.read("OF_Cylinder.msh")
>   File "C:\Python27\lib\site-packages\meshio\helpers.py", line 176, in read
>     return format_to_reader[file_format].read(filename)
>   File "C:\Python27\lib\site-packages\meshio\msh_io\main.py", line 15, in read
>     mesh = read_buffer(f)
>   File "C:\Python27\lib\site-packages\meshio\msh_io\main.py", line 31, in read_buffer
>     assert line == "$MeshFormat"
> AssertionError
> ```

and this error in meshio 4.3.10 by python 3.8:

Traceback (most recent call last):
  File "F:/.../mesh change.py", line 9, in <module>
    mesh = meshio.read("OF_Cylinder.msh", file_format= "ansys-ascii")
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python38\lib\site-packages\meshio\_helpers.py", line 67, in read
    raise ReadError(msg)
meshio._exceptions.ReadError: Unknown file format 'ansys-ascii' of 'OF_Cylinder.msh'.

What is problems with the written codes in each of meshio versions 2.3.10 and 4.3.10?

**Comment by alisheikholeslam** [comment]
> By mesh file that I created in gmsh 2 format, the following error appeared in the PFC software, when It was called by FiPy library. I would be appreciated if you could advice me to solve this error:
> 
> File "C:\Program Files\Itasca\PFC500\exe64\python27\lib\site-packages\fipy\meshes\factoryMeshes.py", line 111, in Grid3D
> if numerix.getShape(dx) == () File "C:\Program Files\Itasca\PFC500\exe64\python27\lib\site-packages\fipy\tools\numerix.py", line 242, in getShape
> raise AttributeError, "No attribute 'shape'"
> AttributeError: No attribute 'shape'

This problem went away. It was my mistake in FiPy usage.

**Comment by alisheikholeslam** [comment]
Before anything else, thank you for your follow-up and responses dear Mr. Schlömer,

I'm confused in using meshio, I couldn't find out what is my mistake and how to solve following problems by meshio modules:
```
import meshio                        # using v 2.3.10 and 4.3.10 in python 2.7 and 3.8, respectively, by PyCharm
mesh = meshio.read("C:\Users\Ali\Desktop\SandPro.vtk")                working
meshio.write("mesh.msh", mesh, file_format="gmsh2-ascii")            working

meshio-info Ansys/OF_Cylinder.msh -i ansys                                     didn't work
meshio-ascii SandPro.vtk                                                                    didn't work
meshio-convert SandPro.vtk A_SandPro.msh                                     didn't work
```

errors are same as follows:

> ```
> meshio-convert SandPro.vtk SandPro.msh 
> 
>   File "C:/Users/Ali/Desktop/mesh change.py", line 12
>     meshio-convert SandPro.vtk SandPro.msh
>                          ^
> SyntaxError: invalid syntax
> ```

Why these errors appear when I'm using meshio?? meshio.read and meshio.write working well, but the others didn't work.
How to use 'meshio-convert' to read an addressed mesh file (which perhaps be in binary format) and convert it to an ascii mesh file (gmsh format 2, as gotten file_format="gmsh2-ascii" in meshio.write), without read and write modules.

**Comment by keurfonluu** [comment]
@alisheikholeslam `meshio-convert` is a command line tool. You must use it outside of your Python interpreter. For instance, you can run it from a Windows console or a Bash terminal.

**Comment by alisheikholeslam** [comment]
> @alisheikholeslam `meshio-convert` is a command line tool. You must use it outside of your Python interpreter. For instance, you can run it from a Windows console or a Bash terminal.

I want to place this code line in a python file, how to do so? could I?

**Comment by keurfonluu** [comment]
> I want to place this code line in a python file, how to do so? could I?

Why do you want to use this command line while you can just do?

```python
import meshio

meshio.read("SandPro.vtk").write("SandPro.msh")
```

**Comment by alisheikholeslam** [comment]
> > I want to place this code line in a python file, how to do so? could I?
> 
> Why do you want to use this command line while you can just do?
> 
> ```python
> import meshio
> 
> meshio.read("SandPro.vtk").write("SandPro.msh")
> ```

I think it must be as follows which does not look good:
```
meshio.write("mesh.msh", meshio.read("C:\Users\Ali\Desktop\B_VTKformat.vtk"), file_format="gmsh2-ascii")
```
your code facing with the following error:
```
Traceback (most recent call last):
  File "F:/.../mesh change.py", line 9, in <module>
    meshio.read("C:\Users\Ali\Desktop\B_VTKformat.vtk").write("mesh.msh", file_format="gmsh2-ascii")
AttributeError: 'Mesh' object has no attribute 'write'
```

Aim of this one-line code is to use that in part of another code, and as a temporary created file, not a made output file, which must be deleted after end of the run. I don't want any exported file that be written on hard drive.

**Comment by keurfonluu** [comment]
Which version of Python? `Mesh.write` only works with `meshio >= 3.0` so it won't work with Python 2.7.
